put:
	aws --endpoint-url=http://localhost:4566 ssm put-parameter --name "/my/parameter" --value "my_value" --type "String" --region us-east-1

get:
	aws --endpoint-url=http://localhost:4566 ssm get-parameter --name "/my/parameter"
